"""
Build rifle-optic blueprint profiles from public US design-patent drawings.

  python3 scripts/pistol-profiles/optics.py   # writes src/data/opticProfiles.ts

  Holographic sight (EOTech EXPS):   US D662,566 S, FIG. 6  https://patents.google.com/patent/USD662566S1
  Micro red dot on its mount:        US D856,458 S, FIG. 5  https://patents.google.com/patent/USD856458S1
Each drawing is turned to a right-side view (rear on the left), and scaled to the length given below.
Coordinates are inches: x from the rear, y up from the bottom of the mount (negative is up).
Uses the same tracing steps as trace.py (silhouette for the outline, thinned solid lines for the details).
"""
import json, os, subprocess, sys
import cv2, numpy as np
from skimage.morphology import skeletonize

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from trace import CACHE, ROOT, flat, silhouette, smooth, trace_skeleton  # noqa: E402

OUT = os.path.join(ROOT, 'src', 'data', 'opticProfiles.ts')

REFS = {
  'holo': dict(
    pdf='https://patentimages.storage.googleapis.com/01/7c/b6/f12311ee6aa803/USD662566.pdf', page=13, im='-flop',
    # Crop to the figure; 3.8" long (EXPS3 published length), base of the mount at the bottom of the crop.
    box=(395, 790, 2165, 2132), length=3.8, axis=1040, th=40, merge=3,
  ),
  'micro': dict(
    pdf='https://patentimages.storage.googleapis.com/5d/5f/f6/ad523606690034/USD856458.pdf', page=6, im='-rotate 90',
    box=(765, 555, 2335, 1772), length=2.47, axis=1080, th=70, merge=3,
  ),
}


def fetch(key, c):
    os.makedirs(CACHE, exist_ok=True)
    pdf = os.path.join(CACHE, 'optic-' + key + '.pdf')
    png = os.path.join(CACHE, 'optic-' + key + '.png')
    if not os.path.exists(png):
        if not os.path.exists(pdf):
            import urllib.request
            urllib.request.urlretrieve(c['pdf'], pdf)
        stem = os.path.join(CACHE, 'optic-' + key + '-raw')
        subprocess.run(['pdftoppm', '-r', '300', '-png', '-f', str(c['page']), '-l', str(c['page']), '-singlefile', pdf, stem], check=True)
        subprocess.run(['convert', stem + '.png', *c['im'].split(), '-colorspace', 'Gray', png], check=True)
    return cv2.imread(png, 0)


def run(key, c):
    full = fetch(key, c)
    bx0, by0, bx1, by1 = c['box']
    img = np.full_like(full, 255)
    img[by0:by1, bx0:bx1] = full[by0:by1, bx0:bx1]
    H, W = img.shape
    ink = (img < 170).astype(np.uint8)
    n, lab, st, _ = cv2.connectedComponentsWithStats(ink, connectivity=8)
    keep = np.maximum(st[:, 2], st[:, 3]) >= c['th']; keep[0] = False
    lines = keep[lab]
    sil = silhouette(np.where(lines, 0, 255).astype(np.uint8))
    sil = smooth(sil, blur=1.2)
    ys, xs = np.nonzero(sil)
    x0, y0 = xs.min(), ys.max()
    s = c['length'] / (xs.max() - x0)
    X = lambda v: round((float(v) - x0) * s, 3)
    Y = lambda v: round((float(v) - y0) * s, 3)

    cs, _ = cv2.findContours(sil.astype(np.uint8), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    cs = [cc for cc in cs if cv2.contourArea(cc) > 2000]
    edge = np.zeros((H, W), np.uint8)
    cv2.drawContours(edge, cs, -1, 255, 9)
    mk = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (c['merge'], c['merge']))
    sk = skeletonize((cv2.morphologyEx(lines.astype(np.uint8), cv2.MORPH_CLOSE, mk) > 0) & sil)
    det = []
    for ln in trace_skeleton(sk):
        seg = []
        for x, y in ln + [(-1, -1)]:
            if x >= 0 and not edge[y, x]:
                seg.append((x, y))
                continue
            if len(seg) >= 10:
                det.append(seg)
            seg = []
    detail = []
    for seg in det:
        p = cv2.approxPolyDP(np.array(seg, np.float32), 1.0, False).reshape(-1, 2)
        detail.append(flat([(X(x), Y(y)) for x, y in p]))
    outline = [flat([(X(x), Y(y)) for x, y in cv2.approxPolyDP(cc.astype(np.float32), 1.2, True).reshape(-1, 2)]) for cc in cs]
    out = {'w': X(xs.max()), 'h': -Y(ys.min()), 'axis': -Y(c['axis']), 'outline': outline, 'detail': detail}
    print(key, out['w'], out['h'], out['axis'], len(outline), len(detail), sum(len(d) // 2 for d in detail), file=sys.stderr)
    return out


def main():
    data = {k: run(k, c) for k, c in REFS.items()}
    body = json.dumps(data, separators=(',', ':'))
    with open(OUT, 'w') as fh:
        fh.write('/* Generated by scripts/pistol-profiles/optics.py from EOTech and micro red dot design-patent drawings. Do not edit by hand. */\n')
        fh.write('/* Inches: x from the rear, y up from the bottom of the mount (negative is up); axis is the sight line\'s height. */\n')
        fh.write('export interface OpticProfile { w: number; h: number; axis: number; outline: number[][]; detail: number[][] }\n\n')
        fh.write(f'export const OPTIC_PROFILES: Record<\'holo\' | \'micro\', OpticProfile> = {body};\n')
    print('wrote', OUT, len(body), 'bytes', file=sys.stderr)


if __name__ == '__main__':
    main()
